[package]
name = "runtime-cost"
version = "0.1.0"
edition = "2018"

[dependencies]
jlib-sys = { path = "jlib-sys", version = "0.1.0" } 

[dev-dependencies]
criterion = "0.3"
criterion-linux-perf = "0.1"

[[bench]]
name = "cost"
harness = false
