sudo: required
dist: trusty
language: coq
branches:
  only:
  - master
services:
- docker
env:
- TARGETS=coq
- TARGETS=compiler
before_install:
- docker pull jasminlang/test-box
script:
- >-
  docker run -v $PWD:/home/ci/jasmin jasminlang/test-box
  sh -c "opam config exec -- make -C jasmin/travis check-${TARGET}"
