sudo: required
dist: trusty
language: coq
branches:
  only:
  - master
services:
- docker
env:
- COQV=8.5.3-1.6.1 TARGET=coq
- COQV=8.5.3-1.6.1 TARGET=compiler
- COQV=8.6-1.6.1   TARGET=coq
before_install:
- docker pull jasminlang/test-box:${COQV}
script:
- >-
  docker run -v $PWD:/home/ci/jasmin jasminlang/test-box:${COQV}
  sh -c "opam config exec -- make -C jasmin/travis check-${TARGET}"
