sudo: required
dist: trusty
language: coq
branches:
  only:
  - master
services:
- docker
notifications:
  email:
  - false
env:
- COQV=8.6-1.6.1 TARGET=compiler
- COQV=8.6-1.6.1 TARGET=coq
before_install:
- docker pull jasminlang/test-box:${COQV}
script:
- >-
  docker run -v $PWD:/home/ci/jasmin:rw jasminlang/test-box:${COQV}
  sh -c "opam config exec -- make -C jasmin/travis check-${TARGET}"
